name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./user/pom.xml
          mvn clean package -f ./plan/pom.xml
          mvn clean package -f ./review/pom.xml
          mvn clean package -f ./diary/pom.xml
          mvn clean package -f ./order/pom.xml
          mvn clean package -f ./payment/pom.xml
          mvn clean package -f ./read/pom.xml

      - name: Docker Build and push for User
        uses: docker/build-push-action@v4
        with:
          context: ./user
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/user:latest
            ghcr.io/${{ github.repository }}/user:${{ github.ref_name }}
            
      - name: Docker Build and push for Plan
        uses: docker/build-push-action@v4
        with:
          context: ./plan
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/plan:latest
            ghcr.io/${{ github.repository }}/plan:${{ github.ref_name }}
            
      - name: Docker Build and push for Review
        uses: docker/build-push-action@v4
        with:
          context: ./review
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/review:latest
            ghcr.io/${{ github.repository }}/review:${{ github.ref_name }}
            
      - name: Docker Build and push for Diary
        uses: docker/build-push-action@v4
        with:
          context: ./diary
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/diary:latest
            ghcr.io/${{ github.repository }}/diary:${{ github.ref_name }}
            
      - name: Docker Build and push for Order
        uses: docker/build-push-action@v4
        with:
          context: ./order
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/order:latest
            ghcr.io/${{ github.repository }}/order:${{ github.ref_name }}
            
      - name: Docker Build and push for Payment
        uses: docker/build-push-action@v4
        with:
          context: ./payment
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/payment:latest
            ghcr.io/${{ github.repository }}/payment:${{ github.ref_name }}
            
      - name: Docker Build and push for Read
        uses: docker/build-push-action@v4
        with:
          context: ./read
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/read:latest
            ghcr.io/${{ github.repository }}/read:${{ github.ref_name }}
            
